const express = require('express');
const cors = require('cors');
const authRoutes = require('./routes/auth');
const adminRoutes = require('./routes/admin');
const projects = require('./routes/projects');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/auth', authRoutes);
app.use('/admin', adminRoutes);
app.use('/projects', projects);
app.get('/', (req,res)=>res.json({ hello:'ok' }));
module.exports = app;
